### ISSUE TITLE
Tesla errors on sending webmentions

### ISSUE THREAD

**Issue by jpcaruana** [ckruse/webmentions-elixir#52]
Hi,

I have been using this Webmention library for a long time (even contributed a bit to it long ago), and I now encounter issues in using it. Maybe it is a combination of erlang/elixir/deps version that do not work well together.

To reproduce the issue, I have an Elixir script:

```elixir
# send_webmention.exs
#! /usr/bin/env elixir
Mix.install([{:webmentions, "~> 3.0.0"}])

defmodule Sender do
  def send_webmention(source) do
    IO.puts("Sending webmentions to #{inspect(source)}")
    {:ok, webmention_response} = Webmentions.send_webmentions(source)
    Enum.each(webmention_response, fn x -> IO.puts("- #{inspect(x)}\n") end)
    IO.puts("DONE Sending webmentions to #{inspect(source)}")
  end
end

Enum.map(
  System.argv(),
  fn source ->
    Task.async(fn -> Sender.send_webmention(source) end)
  end
)
|> Task.await_many(:infinity)

IO.puts("All done!")
```

When I run it, it installs the following deps:

```
Resolving Hex dependencies...
Resolution completed in 0.131s
New:
  floki 0.34.3
  mime 2.0.5
  tesla 1.4.4
  webmentions 3.0.0
* Getting webmentions (Hex package)
* Getting floki (Hex package)
* Getting tesla (Hex package)
* Getting mime (Hex package)
You have added/upgraded packages you could sponsor, run `mix hex.sponsor` to learn more
==> floki
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 29 files (.ex)
Generated floki app
==> mime
Compiling 1 file (.ex)
Generated mime app
==> tesla
Compiling 29 files (.ex)
warning: use Bitwise is deprecated. import Bitwise instead
  lib/tesla/middleware/retry.ex:51: Tesla.Middleware.Retry (module)

warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
  lib/tesla/middleware/logger.ex:154: Tesla.Middleware.Logger (module)

Generated tesla app
==> webmentions
Compiling 3 files (.ex)
Generated webmentions app
All done!
```

But when I run it, I get this `1st argument: not an atom` error within `Tesla.Middleware.FollowRedirects`

```bash
$ ./send_webmention.exs https://some.url/with_mentions/
Sending webmentions to "https://some.url/with_mentions/"
** (EXIT from #PID<0.98.0>) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an atom

        :erlang.atom_to_binary({Tesla.Middleware.FollowRedirects, :too_many_redirects})
        (webmentions 3.0.0) lib/webmentions.ex:175: Webmentions.discover_endpoint/1
        (webmentions 3.0.0) lib/webmentions.ex:99: Webmentions.handle_send_webmention/2
        (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (webmentions 3.0.0) lib/webmentions.ex:89: Webmentions.send_webmentions_for_links/3
        send_webmention.exs:7: Sender.send_webmention/1
        (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2


13:40:45.839 [error] Task #PID<0.200.0> started from #PID<0.98.0> terminating
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an atom

    :erlang.atom_to_binary({Tesla.Middleware.FollowRedirects, :too_many_redirects})
    (webmentions 3.0.0) lib/webmentions.ex:175: Webmentions.discover_endpoint/1
    (webmentions 3.0.0) lib/webmentions.ex:99: Webmentions.handle_send_webmention/2
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (webmentions 3.0.0) lib/webmentions.ex:89: Webmentions.send_webmentions_for_links/3
    send_webmention.exs:7: Sender.send_webmention/1
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<1.32386323 in file:send_webmention.exs>
    Args: []
```

```
 $ elixir --version
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

```
$ erl
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
```

If you have any suggestion or idea to help understand (and fix) this issue, it would be great!

Thanks

**Comment by jpcaruana** [comment]
I also encounter this issue on my server with different elixir/erlang versions:

```bash
$ elixir --version
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Elixir 1.14.1 (compiled with Erlang/OTP 25)
```

```bash
$ erl
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Eshell V13.1.1  (abort with ^G)
```

```bash
$ ./send_webmention.exs https://some.url/with_mentions/
Resolving Hex dependencies...
Resolution completed in 0.187s
New:
  floki 0.34.3
  mime 2.0.5
  tesla 1.4.4
  webmentions 3.0.0
* Getting webmentions (Hex package)
* Getting floki (Hex package)
* Getting tesla (Hex package)
* Getting mime (Hex package)
You have added/upgraded packages you could sponsor, run `mix hex.sponsor` to learn more
==> floki
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 29 files (.ex)
Compiling lib/floki/entities/codepoints.ex (it's taking more than 10s)
Generated floki app
==> mime
Compiling 1 file (.ex)
Generated mime app
==> tesla
Compiling 29 files (.ex)
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
  lib/tesla/middleware/logger.ex:154: Tesla.Middleware.Logger

warning: use Bitwise is deprecated. import Bitwise instead
  lib/tesla/middleware/retry.ex:51: Tesla.Middleware.Retry

Generated tesla app
==> webmentions
Compiling 3 files (.ex)
Generated webmentions app
Sending webmentions to "https://some.url/with_mentions/"

13:49:41.156 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:44.277 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:44.888 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:45.246 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:45.361 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:49.114 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:53.763 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:57.071 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'


13:49:57.581 [error] Task #PID<0.934.0> started from #PID<0.95.0> terminating
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an atom

    :erlang.atom_to_binary({Tesla.Middleware.FollowRedirects, :too_many_redirects})
    (webmentions 3.0.0) lib/webmentions.ex:175: Webmentions.discover_endpoint/1
    (webmentions 3.0.0) lib/webmentions.ex:99: Webmentions.handle_send_webmention/2
    (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (webmentions 3.0.0) lib/webmentions.ex:89: Webmentions.send_webmentions_for_links/3
    send_webmention.exs:7: Sender.send_webmention/1
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Function: #Function<1.127739544 in file:send_webmention.exs>
    Args: []
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an atom

        :erlang.atom_to_binary({Tesla.Middleware.FollowRedirects, :too_many_redirects})
        (webmentions 3.0.0) lib/webmentions.ex:175: Webmentions.discover_endpoint/1
        (webmentions 3.0.0) lib/webmentions.ex:99: Webmentions.handle_send_webmention/2
        (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (webmentions 3.0.0) lib/webmentions.ex:89: Webmentions.send_webmentions_for_links/3
        send_webmention.exs:7: Sender.send_webmention/1
        (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2

```

**Comment by ckruse** [comment]
I released a new version on hex.pm with your fix.
